// export all generic components here
export {  Menu } from './Menu/Menu';
export { LangMenu } from './LangMenu/LangMenu';
export { CustomSlider } from './CustomSlider/CustomSlider';
export { ExchangeRate } from './ExchangeRate/ExchangeRate';
export { PrivateRoute } from './PrivateRoute/PrivateRoute';
export { Card } from './Card/Card';
export { Piggy } from './Piggy/Piggy';
export { Transaction } from './Transaction/Transaction';
